---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos-euw6 
  namespace: argocd 
spec:
  project: app-bank-of-anthos 
  source:
    repoURL: https://github.com/timbohiatt/time-keeper-v3-apps-boa.git 
    targetRevision: HEAD
    path: deployment/manifests
  destination:
    server: https://192.168.0.2
    namespace: app-bank-of-anthos
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-of-anthos-ausse1
  namespace: argocd 
spec:
  project: app-bank-of-anthos
  source:
    repoURL: https://github.com/timbohiatt/time-keeper-v3-apps-boa.git 
    targetRevision: HEAD
    path: deployment/manifests
  destination:
    server: https://172.16.0.18
    namespace: app-bank-of-anthos
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
